---
- name: Update and Upgrade
  hosts: localhost  # Replace with your target hosts or IP addresses
  become: true  # Run tasks with administrative privileges

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Get IP address
      ansible.builtin.set_fact:
        host_ip: "{{ ansible_default_ipv4.address }}"

    - name: Get Hostname
      ansible.builtin.set_fact:
        host_name: "{{ ansible_hostname }}"

    - name: Display IP address and Hostname
      debug:
        msg: "IP Address: {{ host_ip }}, Hostname: {{ host_name }}"
